[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wd14-tagger-standalone"
version = "0.0.1"
dependencies = [
    "pandas~=2.2",
    "huggingface-hub~=0.22",
    "Pillow~=10.0",
    "deepdanbooru~=1.0",
    "onnxruntime~=1.17",
    "numpy~=1.26",
    "opencv-python~=4.9",
]